### ISSUE TITLE
Customer Requisitions

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#100]
[ should this be renamed? ]

- [x] View a list of all customer requisitions for the currently logged in store
- [x] Filter the list of customer requisitions with various options ( expand on options )
- [x] View an existing customer requisition
- [x] Create a new customer requisition
- [x] Add lines to a customer requisition
- [x] Edit quantities of lines within a customer requisition
- [x] Finalise a customer requisition
- [x] Add notes to a customer requisition
- [x] Save the sort order of lines in a requisition (?? )
- [x] Delete lines in the customer requisition
- [x] Print a copy of the customer requisition
- [x] View details of the customer requisition ( expand on details: requisition number, entry date, status, etc )
- [ ] View a details log of all interactions with the customer requisition
- [ ] View a summary of invoices created from the customer requisition ( what shows here? )
- [x] Change the 'colour' of the customer requisition ( what is the colour? )
- [x] Add a comment to the customer requisition
- [x] Add a other party reference to the customer requisition
- [ ] Create a customer requisition by selecting a program, order type and period
- [x] Each lines has the columns: .. ( TODO: expand on the columns! )
- [x] Change the requisition date of a customer requisition
- [x] Change the order received date of a customer requisition
- [ ] Set automatically set the quantity to be supplied for every line to be equal to the requested quantity.
- [x] Populate a customer requisition by selecting a master list
- [x] Create a customer invoice from the details and some subset of the lines from the customer requisition

**Comment by richardmoizeau** [comment]
working on the navigation and especially the requisition, the more I think about it the more I like the idea of:
Supplier Requisitions => Requisitions
Customer Requisitions => Customer Orders
It's quite a big change and could be confusing cause currently we have two names for Requisitions and one them contains the word "order" (Internal Order). What do you think ?

**Comment by mark-prins** [comment]
Doesn't that also mean 
Internal Orders => Requisitions

So we end up with 
- Customer Orders ( which used to be `Customer Requisitions` )
- Requisitions ( which used to be `Internal Orders` )

and therefore we have `Requisitions` which can be confusing if you are trying to find the old `Customer Requisitions` 
and we have `Customer Orders` which can be confusing if you are trying to find the old `Internal Orders`

I actually think the new names work well, and I have struggled with the old names ( as a non-accountant, `Customer Invoice` had no natural meaning to me! ). I'm just exploring whether this will be a problem for existing users.

**Comment by mark-prins** [comment]
Moved to https://github.com/openmsupply/org-issues/issues/51
