### ISSUE TITLE
Customer Credits

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#101]
- [ ] View a list of all customer credits for the currently logged in store
- [ ] Filter the list of customer credits with various options ( TODO: define options )
- [ ] View an existing customer credit
- [ ] Create a new customer credit
- [ ] Add lines to a customer credit
- [ ] Edit quantities of lines within a customer credit
- [ ] Finalise a customer credit
- [ ] Add notes to a customer credit
- [ ] Save the sort order of lines in a credit (??)
- [ ] Delete lines in the customer credit
- [ ] Print the customer credit
- [ ] View details of the customer credit ( Expand on details: requisition number, entry date, status, etc )
- [ ] View a details log of all interactions with the customer credit
- [ ] View a summary of invoices created from the customer credit ( TODO: what shows here? )
- [ ] Change the 'colour' of the customer credit ( what is the colour? )
- [ ] Add a comment to the customer credit
- [ ] Add a other party reference to the customer credit
- [ ] Each lines has the columns: .. ( TODO: define the columns )
- [ ] Select lines from the customers history

**Comment by mark-prins** [comment]
Moved to https://github.com/openmsupply/org-issues/issues/50
