### ISSUE TITLE
Cold Chain

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#102]
Full cold chain equipment monitoring

- [ ] Receive sensor logs over HTTP
- [ ] Alert users to a temperature breach
- [ ] Forward data to central server

**Comment by mark-prins** [comment]
Moved to https://github.com/openmsupply/org-issues/issues/49
