### ISSUE TITLE
Shared Functionality

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#110]
- [ ] Manufacturers
  - [ ]  view a list of manufacturers
- [x] Customers
  - [x]  view a list of customers
- [x] Suppliers
  - [x]  view a list of suppliers
- [ ] Name categories
  - [ ]  view a list of supplier categories
  - [ ]  view a list of customer categories
- [ ] Logs
  - [ ] View a log of all user actions
  - [ ] Log all user activity

**Comment by joshxg** [comment]
>  Logs
>  View a log of all user actions
>  Log all user activity

I know you've got this in the background but I think this is worth flagging.. because if we really want a log of all user activity, there really isn't a better way to do that than redux 🤣

**Comment by mark-prins** [comment]
Oh my. yes, it is a good idea! though if feels like redux is trying to lure us back.. all roads lead to redux?

**Comment by joshxg** [comment]
seems that way 🙄

**Comment by mark-prins** [comment]
Shifted to https://github.com/openmsupply/org-issues/issues/41
