### ISSUE TITLE
Detail Panel : Additional stuff

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#359]
In addition to #302 there is some more data to show in the panel. Ideally, the first section is open by default to reduce a click for access to the most useful info

**Shipment details (or additional info?)**
- [x] Colour (colour picker) #380
- [x] Entered on date (wonder if it is necessary since we have the status details on the bottom left corner) #382
- [x] Entered by username #382
- [x] Comment #382

**Donor**
- [ ] Donor : to assign a donor to the shipment, selected from a list (included in v1 ?) ( I thought it could be in section one but the email said 'separate section' ) - #383

**Related Documents**
- [x] #384 Requisition number (if created against a requisition)
- [x] #384  PO number (if created against a PO)
- [x] #384  Good Receipt number (if created against a GR and if we are using GR still)
- [x] #384  When shipped, the Inbound Shipment number ? 

**Categories**
- [ ] #385 A select of some sort, with data from somewhere and a way to add more ( +button? ) 2 categories at the moment

**Transport Details**
- [ ] #386 Shipping Method: drop down (Air, Truck, Sea, Drone)
- [ ] #386 Transport Reference: free text. eg. Air way bill number, tracking number

**Invoice details (?)** ( this is #302 )
- [x] #302 Subtotal: automatically calculated
- [x] #302 0% tax: you can edit the % / tax amount is automatically calculated
- [x] #302 Total: automatically calculated

Note:  Other Charges is replaced by service lines

**Comment by joshxg** [comment]
https://github.com/openmsupply/openmsupply-client/issues/380
