### ISSUE TITLE
API Change requests

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#827]
Just starting a list here for api change requests

### Requisitions
- [x] Charts: https://github.com/openmsupply/remote-server/issues/809

### Invoices
- [ ] `InboundShipmentLine.sentNumberOfPacks`  / `InboundShipmentLine.sentPackSize` https://github.com/openmsupply/remote-server/issues/706 (added to that issue, let me know if linked invoice line resolver is needed to display this)
- [x] Allocate placeholders mutation: https://github.com/openmsupply/remote-server/issues/885
- [ ] Inbound line tax update https://github.com/openmsupply/remote-server/issues/947
- [x] inbound totals not updated https://github.com/openmsupply/remote-server/issues/923
- [ ] Outbound `addFromMasterList` mutation https://github.com/openmsupply/openmsupply-client/issues/1015
- [x] `InvoiceFilterInput.otherPartyType` - Need to filter out inbound shipments with `otherPartyType === 'invad'`

### Items
- [x] See also [#513](https://github.com/openmsupply/remote-server/issues/513)

### Names
- [x] hold (from docs: "If this is checked this name can not be used for receiving or issuing goods")

### User
- [x] Expose the stores the user is able to log into `availableStores` / `availableStoresOnSite` 🤔 ?
- [x] Created by : https://github.com/openmsupply/remote-server/issues/808

### Suggestions / options (can ignore)**
- [ ]  `RequisitionLineNode.itemStats` -> `snapshotItemStats` - making the distinction between this and `RequisitionLineNode.item.stats` clearer https://github.com/openmsupply/remote-server/issues/811

**Comment by joshxg** [comment]
### Item
- Available quantity

**Comment by andreievg** [comment]
Added a grouping issue: https://github.com/openmsupply/remote-server/issues/805, and issues to the bulletpoints.

Have `urgency` label now in b/e, would be great if you can mark at least `immediate` or 1-2 days urgency issues. Cheers

**Comment by joshxg** [comment]
@mark-prins this is what I'm thinking

I'm thinking the ones which would be ideal to have first to minimise code changes:
- https://github.com/openmsupply/remote-server/issues/802
- https://github.com/openmsupply/remote-server/issues/807

Then big cross cutting:
- https://github.com/openmsupply/remote-server/issues/806

Then if these ones are done in whatever order is best:
- https://github.com/openmsupply/remote-server/issues/799
- https://github.com/openmsupply/remote-server/issues/800
- https://github.com/openmsupply/remote-server/issues/801
- https://github.com/openmsupply/remote-server/issues/803
- https://github.com/openmsupply/remote-server/issues/804

These ones can be last/discussed:
- https://github.com/openmsupply/remote-server/issues/808
- https://github.com/openmsupply/remote-server/issues/809

**Comment by joshxg** [comment]
Have labelled the issues with no PRs, mainly with 1 week, batched mutations for reqs a little sooner, think that ones pretty easy though!

The reqs chart/users issues I've not labelled as I think they need a little more discussion

**Comment by joshxg** [comment]
@andreievg 

Have added another 😁 

- `UpdateRequisitionLineInput.comment`

**Comment by joshxg** [comment]
Have updated with results of https://github.com/openmsupply/openmsupply-client/issues/918

**Comment by joshxg** [comment]
Added:

- RequisitionSortFieldInput.comment

**Comment by joshxg** [comment]
Added

- `StockLineNode.item`

**Comment by joshxg** [comment]
Added

- Store: `StoreNode.name`

**Comment by joshxg** [comment]
Added:

- `InsertOutboundShipmentLineInput.tax` v `OutboundOutboundShipmentLineInput.tax` - consistency of either a `float` or `TaxUpdate` type [Same with inbound]
- `InvoiceNode.tax` - expose to be queried

**Comment by joshxg** [comment]
Suggestion:

- `addFromMasterList` should be renamed it's too specific. Customer invoices also have add from master list, and there are likely other cases where this could make this not ideal for a name. Better to change earlier rather than later.

**Comment by joshxg** [comment]
Added: 
- store sorting [we have page/filtering, no sorting]

**Comment by joshxg** [comment]
Added:

- `InboundShipmentLine.sentNumPacks` / `sentPackSize` : mSupply has a field `sentQuantity`, which is the actual quantity sent (potentially different to what the supplier said).

**Comment by joshxg** [comment]
Added

- Allocate placeholders mutation https://github.com/openmsupply/remote-server/issues/885

**Comment by andreievg** [comment]
>  Search by other party name
> RequisitionSortFieldInput.comment

Looks like this is there already

**Comment by andreievg** [comment]
> UpdateStocktakeLineInput -remove snapshot num packs from update input

I think this one is there so that snapshot number of packs can be updated, there is an error when stocktake is finalise `SnapshotCountCurrentCountMismatch`, which return lines for which snapshot number of packs have changed since stocktake was started. I think Clemens added snapshot number of pack on update mutation to allow front end to handle this (not sure what UI for this is).  Can potentially expose a mutation `refreshSnapshotNumberOfPacks` (takes stocktake and an optional array of line ids to update, if optional array is not specified would update all lines)

**Comment by andreievg** [comment]
> InvoiceNode.tax - expose to be queried

Do you mean to be filterable and sortable ? Otherwise it's available through InvoicePriceNode of InvoiceNode.pricing

**Comment by joshxg** [comment]
> Do you mean to be filterable and sortable ? Otherwise it's available through InvoicePriceNode of InvoiceNode.pricing

Should have been InvoiceLineNode.tax. Because the tax in on the line, we need an input for tax on a line, which should be the previous user entered value

**Comment by joshxg** [comment]
> refreshSnapshotNumberOfPacks (takes stocktake and an optional array of line ids to update, if optional array is not specified would update all lines)

This isn't in mSupply (as far as I can tell) and hasn't been put as a requirement. We've not got anything for refreshing snapshots. Though, your mutation sounds like a good idea if it is required.

User updating snapshots just seemed like not a good idea.

**Comment by andreievg** [comment]
> User updating snapshots just seemed like not a good idea.
Summed up here, post pone till after v1
https://github.com/openmsupply/remote-server/issues/895

**Comment by joshxg** [comment]
Added:

- [name]onHold
- [name]margin
- [item]defaultPrice
- [item]margin

**Comment by joshxg** [comment]
Added:
- [ ] Inbound line tax update

**Comment by joshxg** [comment]
Added:

- `StoreNode.name` - Need a storeID to query for the store name, but don't need a name for stores. This makes querying for a list of stores and their names to display for logging in difficult

**Comment by mark-prins** [comment]
Added note about item issue

**Comment by andreievg** [comment]
this one is filtered out i think `InvoiceFilterInput.otherPartyType - Need to filter out inbound shipments with otherPartyType === 'invad'`

**Comment by josh-griffin** [comment]
Oh, my bad

**Comment by mark-prins** [comment]
👻

**Comment by mark-prins** [comment]
time to close this one - all items are moved to individual issues now

**Comment by josh-griffin** [comment]
<img src='https://media2.giphy.com/media/KctrWMQ7u9D2du0YmD/giphy.gif?cid=5a38a5a25ym6y2wcd9ga2lssivuomxutar0wlbqxsnc3ta6m&rid=giphy.gif&ct=g'/>
