### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#83]
- [x] Login screen #5 
- [x] Authentication api handling #770 
  - Login
  - Logout
- [ ] Change password
- [x] Local storage: JWT?
- [x] Switch store
- [ ] Change account details? (If users are centrally managed for phase 1, then you'd have to use a message to send these changes through to the central server)
- [ ] Be prevented from accessing functionality if they do not have appropriate permissions

**Comment by joshxg** [comment]
Couple other things. I've not done a proper auth workflow before.. a bit of a dump:

- httpOnly cookie to store the session identifier? I've seen some things about local storage/cookies being accessible by scripts so not so safe.
- Storing UI preferences: I.e. what columns has this user set for outbound shipments - local storage? Maybe nothing to do with this 🤔 
- app preferences/permissions 
    - does it matter if these aren't so secure? 
    - Can put in local storage? 
    - Or maybe these are in a JWT? 
    - Do we need to revoke easily?

Probably just a simple system for now? 

1. Request to server
2. Get session id/jwt/token
3. store somewhere
4. never revoke [setup token refresh system later]
5. permissions either in the jwt or sent separately/as a json in the body when logging in? [If you want to change permissions, force a logout until the refresh system in?]

**Comment by mark-prins** [comment]
I like the idea of local storage for UI preferences, I think that it's slightly outside the authentication area though.

The flow proposed by the server team is to login first and then select store - the login call returns allowable stores. Perhaps the switch store method could return permissions for that store? We save that either as another cookie or local storage?

Probably fine to have the permissions readable, my concern is that if they are in a plain format then they could be altered, so it would be good if the server signed them.

Revoking access to server data should be ok, as I understand it all API calls require a token to identify the user, so any removal of access would affect further calls. The problem is with revoking access to areas in the app - I think that we don't need to worry about that, the main time sensitive issue is data access. 

It would help though if we had JWT sessions expiring with a refresh token option in the API

Not sure about the insecurity of cookies, will need to look into that.

**Comment by mark-prins** [comment]
Moved to https://github.com/openmsupply/org-issues/issues/65
