### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#84]
The initial setup and shared elements
- [x] Data table #4 
- [x] API query framework #3 
- [x] Theme #2 #81 
- [x] Hot module replacement #12 
- [x] Minimise bundle size #1 #13 
- [x] Multi lingual support
  - [x] add translations & intl support
  - [x] Detect user language #79 
  - [x] enable fallback translations #113 
- [ ] Logging #53 
- [x] Drawer
  - [x] LHS drawer #39 #56 
  - [x] RSH drawer #49 #167
- [x] common library #27 
- [x] create page not found page #139
- [x] show status: logged in user and store #150 
- [x] Responsive
  - [x] appbar buttons show icon only for small screens #154
- [x] commit hook to redeploy site #123
  - [x] env file for configuration #26 #122
- [x] breadcrumb
  - [x] back arrow #118

**Comment by mark-prins** [comment]
Moved to https://github.com/openmsupply/org-issues/issues/64
