### ISSUE TITLE
Outbound shipments

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#85]
previously known as 'Customer Invoices' 
- [x] View a list of invoices 
  - [ ] Limit list by currently logged in store (requires login and auth tasks)
  - [x] New invoice
  - [x] Filter list ( by various, unspecified, options )
  - [x] Delete invoices

- [ ] Individual invoice
  - [x] View an existing invoice #71
  - [x] Edit invoice
  - [x] Delete lines ( if before shipped )
  - [x] Delete invoice
  - [x] Add line
    - [x] Fetch item list
  - [x] Edit quantities of lines within an invoice
  - [x] Remove line
    - [x] Remove multiple lines ( select dd )
  - [ ] Print page
  - [ ] Export?
  - [x] Comments
  - [ ] History
  - [ ] Fetch history
    - [ ] Create new item line based on history?
  - [x] Save and new
  - [x] change status: 
    - [x] confirm / finalise
    - [x] place on hold
  - [ ] Display errors
  - [x] Auto allocate stock?
  - [x] Allocate stock
  - [x] View per item prices for a line (?)
  - [ ] View the total for a line
  - [ ] View the total price for the entire invoice
  - [ ] Apply a category to an invoice
  - [x] View details of the invoice
  - [ ] View a details log of all interactions with the customer invoice
    - [ ] Expand on details: invoice number, entry date, status etc (etc??)
  - [x] Change the 'colour' of the invoice (necessary?)
  - [x] Add a other party reference to the customer invoice
  - [ ] Add additional, arbitrary charges to the customer invoice
  - [ ] Populate a customer invoice by selecting a requisition.

**Comment by mark-prins** [comment]
Moved to https://github.com/openmsupply/org-issues/issues/63
