### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#86]
- [ ] **Report editor**
  - [ ] Producing local reports- transactions this month, an item stock list, a cross tab report of items X days/months with usages in cells (pivotable-like)
  - [ ] Specify the data source (e.g. transactions, items)
  - [ ] Specify a date range or various other filters.
  - [ ] Save to Excel (or to Clipboard to paste into Excel would also suffice)

**Comment by mark-prins** [comment]
Moved to https://github.com/openmsupply/org-issues/issues/62
