### ISSUE TITLE
Stocktakes

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#93]
- [ ] view a list of all stocktakes for the current store
- [ ] filter the list of stocktakes with various options
- [x] view an existing stocktake
- [ ] create a new stocktake, including prepopulate a stocktake through various options
- [ ] add lines to a stocktake
- [x] edit quantities of lines within a stocktake
- [ ] finalise a stocktake
- [ ] delete a non-finalised stocktake.
- [ ] save their sorting order of lines
- [x] delete lines in the stocktake
- [ ] print a copy of the stocktake
- [x] lock the stocktake for editing
- [ ] create inventory adjustments from the stocktake
- [x] edit various fields on a stocktake

**Comment by mark-prins** [comment]
Moved to https://github.com/openmsupply/org-issues/issues/57
