### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#94]
- [x] View all locations for the currently logged in store
- [x] Create a locationsfor the currently logged in store
- [ ] Soft delete a location in the system (i.e. make it hidden so it's not available for use but it does appear in historical records, includuing for stock that it already in that location)
- [ ] Merge a location in the system
- [x] View details of a location in the system (It's possible a location list might contain all details and no detail view required)
- [x] Edit details of a location - Expand on options (but see previous row)

**Comment by mark-prins** [comment]
Mostly implemented with #555 #510 #711 
Merging, I'll move to phase 2, and the soft delete is an API concern - will need to raise the issue there
