### ISSUE TITLE
Locations ( part II )

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#95]
- [ ] Assign items to a particular location (What does this mean? Restricting by location type, setting a default location or assigning stock to a location?)
- [ ] View all location types in the system (is this needed- when you edit a location you get to see the types in a DDL)
- [ ] Merge a location in the system

**Comment by mark-prins** [comment]
Moved to https://github.com/openmsupply/org-issues/issues/56
