### ISSUE TITLE
Inbound shipments

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#97]
previously known as 'Supplier Invoices' 
- View a list of invoices 
  -  ~Limit list by currently logged in store (requires login and auth tasks)~ yes, but not now
  - [x] New invoice
  - [x] Delete invoice
  - [x] Filter list ( by various, unspecified, options )
  - [x] show comment column, ability to add and edit comments here
- Individual invoice
  - [x] View an existing invoice #71
  - [x] Edit invoice
  - [x] Delete items ( if before shipped )
  - [x] Add item
    - [x] Fetch item list
  - [x] Edit quantities of lines within an invoice
  - [x] Add notes to an inbound shipment
  - [x] Remove item
    - [x] Remove multiple lines ( select dd )
  - [ ] Print page
  - [ ] Export?
  - [x] Comments
    - [x] add a comment
  - [ ] History
    - [ ] Fetch history
    - [ ] Create new item line based on history?
  - [x] Save and new
  - [x] change status: 
    - [x] confirm / finalise
    - [x] place on hold
  - [ ] Display errors
  - [ ] View per item prices for a line (?)
  - [ ] View the total for a line
  - [ ] View the total price for the entire invoice
  - [ ] Apply a category to an invoice
  - [x] View details of the invoice
    - [ ] View a details log of all interactions with the supplier invoice
    - [ ] Expand on details: invoice number, entry date, status etc (etc??)
  - [ ] Extra price functionality (?)
  - [x] Change the 'colour' of the invoice (necessary?)
  - [x] Add a other party reference to the customer invoice
  - ~Add additional, arbitrary charges to the supplier invoice~ (huh?)
  - [ ] Populate a supplier invoice by selecting a requisition
  - [ ] Copy to the clipboard ( details a little lacking, something similar to msupply? )

**Comment by mark-prins** [comment]
moved to https://github.com/openmsupply/org-issues/issues/54
