### ISSUE TITLE
Supplier Credit

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#98]
- [ ] View a list of all supplier credits for the currently logged in store
- [ ] Filter the list of supplier credits with various options ( which are...? )
- [ ] View an existing supplier credit
- [ ] Create a new supplier credit
- [ ] Add lines to a supplier credit
- [ ] Edit quantities of lines within a supplier credit
- [ ] Finalise a supplier credit
- [ ] Add notes to a supplier credit
- [ ] Copy the supplier credit to the clipboard
- [ ] Reapply line numbers to line of a supplier credit
- [ ] A user can delete lines in the supplier credit
- [ ] Print a copy of the supplier credit
- [ ] Place a supplier credit on hold ( what is being put on hold? )
- [ ] View per item prices for a line in a suppplier credit
- [ ] View the total for a line in a supplier credit
- [ ] View the total price for the entire credit
- [ ] Apply a category to an credit
- [ ] View details of the supplier credit (expand on details: invoice number, entry date, status, more stuff...)
- [ ] View a details log of all interactions with the supplier credit
- [ ] See a summary of an item within the credit ( what shows here?? )
- [ ] See a summary of each batch within the credit ( what shows here?? )
- [ ] Change the 'colour' of the credit ( what is the colour? )
- [ ] Add a comment to the supplier credit
- [ ] Add a other party reference to the supplier credit
- [ ] Add additional, arbitrary charges to the supplier credit
- [ ] Populate a supplier credit by selecting a requisition.

**Comment by mark-prins** [comment]
moved to https://github.com/openmsupply/org-issues/issues/53
