### ISSUE TITLE
Supplier Requitision

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#99]
[ new name? ]

- [ ] view a list of all supplier requisitions for the currently logged in store
- [ ] filter the list of supplier requisitions with various options ( options to be defined? )
- [ ] view an existing supplier requisition
- [ ] create a new supplier requisition
- [ ] add lines to a supplier requisition
- [ ] edit quantities of lines within a supplier requisition
- [ ] finalise a supplier requisition
- [ ] add notes to a supplier requisition
- [ ] reapply line numbers to line of a supplier requisition ( ?? )
- [ ] Delete lines in the supplier requisition
- [ ] Print a copy of the supplier requisition
- [ ] View details of the supplier requisition ( expand on details: requisition number, entry date, status, etc )
- [ ] View a details log of all interactions with the supplier requisition
- [ ] See a summary of an item within the requisition ( what shows here? ) 
- [ ] See a summary of each batch within the requisition ( what shows here? )
- [ ] Change the 'colour' of the requisition ( what is the colour? )
- [ ] Add a comment to the supplier requisition ( what's the difference between comments and notes? )
- [ ] Add additional, arbitrary charges to the supplier requisition ( what are "arbitrary" changes? )
- [ ] Create a supplier requisition by selecting a program, order type and period
- [ ] View the total for a line in a supplier requisition
- [ ] View the total price for the entire requisition
- [ ] Apply a category to an requisition
- [ ] Change the max MOS of a requisition ( only editable when not populated by a program requisition )
- [ ] Change the threshold MOS of a requisition
- [ ] Filter lines by being over the threshold MOS of a requisition
- [ ] Populate a supplier requisition by selecting a master list
- [ ] Add a other party reference to the supplier requisition

**Comment by mark-prins** [comment]
moved to https://github.com/openmsupply/org-issues/issues/52
